# export VM_BOX='bento/ubuntu-16.04'
# export VM_BOX='jhcook/macos-sierra'
# export VM_BOX='boxcutter/centos72'

$VM_BOX = ENV.has_key?('VM_BOX') ? ENV['VM_BOX'] : 'bento/ubuntu-16.04'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = $VM_BOX
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision :ansible do |ansible|
    ansible.playbook = 'test.yml'
    ansible.verbose = 'vv'
  end
end
