---
# tasks file for zsh

- include: install_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: install_macos.yml
  when: ansible_os_family == 'Darwin'

- name: zsh | get path
  command: which zsh 
  register: zsh_path
  changed_when: no
  tags: zsh

- name: zsh | switch shell
  become: yes
  user:
    name: "{{ common_user }}"
    shell: "{{ zsh_path.stdout }}"
  tags: zsh

- name: zsh | clone antigen
  become: yes
  git:
    repo: "{{ zsh_antigen_repo }}"
    dest: "{{ common_home }}/.antigen"
    accept_hostkey: yes
    update: no
  tags: [ zsh, antigen ]

- name: zsh | set permissions for antigen
  become: yes
  file:
    path: "{{ common_home }}/.antigen"
    owner: "{{ common_user }}"
    state: directory
    recurse: yes
  tags: [ zsh, antigen ]

- name: zsh | create zshrc file
  become: yes
  template:
    src: zshrc.j2
    dest: "{{ common_home }}/.zshrc"
    owner: "{{ common_user }}"
    mode: 0640
  tags: zsh
