export LS_OPTIONS='--color=auto'

alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias la='ls $LS_OPTIONS -lA'
alias mk='mkdir -p'
alias cp='cp -r'
alias z='cd -'
alias c='clear'
alias t='touch'
alias g='git'
alias v='vim'
alias src='source'
alias findr='find . -iname'
