---
# tasks file for common

- name: get Homebrew location
  command: which brew
  register: common_homebrew_path
  changed_when: no
  tags: [ common, macos ]

- name: install Homebrew
  script: install-homebrew.sh
  when: common_homebrew_path.stdout == ""
  tags: [ common, macos ]

- name: install packages macos
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }}"
  tags: [ common, macos ]
