---
# tasks file for common

- name: check Homebrew location
  stat:
    path: which brew 
  register: common_homebrew_path
  tags: [ common, macos ]

# - name: install Homebrew
#   script: install-homebrew.sh
#   when: not common_homebrew_path.stat.exists
#   tags: [ common, macos ]

- name: install packages macos
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }}"
  tags: [ common, macos ]
