---
# tasks file for common

- include: install_ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: install_macos.yml
  when: ansible_os_family == 'Darwin'

- name: common | copy aliases config files
  copy: src=files/aliases.sh dest={{ common_home }}/.bash_aliases
  tags: common

- name: common | configure vim
  copy: src=files/vimrc dest={{ common_home }}/.vimrc
  tags: common

- name: common | configure git
  copy: src=files/gitconfig dest={{ common_home }}/.gitconfig
  tags: common
